### ISSUE TITLE
PHP 7.2 Class Object problem

### ISSUE THREAD

**Issue by asilvestre87** [geertw/yii2-translatable-url-rule#3]
Hi,
From Yii2 2.0.13 version class Object has been replaced by [[BaseObject]] because `object` has become a reserved word which can not be used as class name in PHP 7.2.

For solve this for new Yii versions: 
- replace **use yii\base\Object;** for **use yii\base\BaseObject ;**
- replace **class TranslatableUrlRule extends Object implements UrlRuleInterface {**  for  **class TranslatableUrlRule extends BaseObject implements UrlRuleInterface {**

https://github.com/yiisoft/yii2/blob/2.0.13/framework/UPGRADE.md#upgrade-from-yii-2012

**Comment by geertw** [comment]
Hi, thanks for the heads-up! Will make a new version which uses `BaseObject`.
